Update `pyo3::ffi` struct definitions to be compatible with 3.12.0b4.
